## NUMPY DATA MANIPULATION FULL A-Z

In [1]:
import numpy as np

In [2]:
np.array([1,"hello",3])

array(['1', 'hello', '3'], dtype='<U11')

In [3]:
#2d arrays
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
#min dim 2:
np.array([1,2],ndmin=5)

array([[[[[1, 2]]]]])

In [11]:
#dtype
dtype=np.array([1,2,3],dtype=complex)
dtype

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
#data-type consisting more than one element
np.array([(1,2),(3,4)],dtype=[("a","<i2"),("b","<i8")])

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [21]:
x=np.array([[1,2],[3,4]])
print(x[0])
print(x[1])
print(x[0][0])
print(x[0][1])
print(x[1][0])
print(x[1][1])

[1 2]
[3 4]
1
2
3
4


In [22]:
#matrix
np.mat([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

### numpy.asarray()

In [23]:
#it will convert input to array
#also list to array

In [24]:
a=[1,2]
np.asarray(a)

array([1, 2])

In [26]:
a=[[1,1]]
np.asarray(a)

array([[1, 1]])

In [27]:
a=[[1,1]]
np.asarray(a,dtype=np.float32)

array([[1., 1.]], dtype=float32)

In [30]:
issubclass(np.ndarray,np.matrix)

False

### numpy.asanyarray

In [34]:
a=np.mat([1,1])
np.asanyarray(a)#it will not convert mat to arr

matrix([[1, 1]])

In [36]:
#create an array with a reference y and a copy z
x=np.array([1,2,3])
y=x#solo copy

In [46]:
z=y.copy()#it will not reflect changes
#deep copy
print(z.astype(float))
y

[1. 2. 3.]


array([1, 2, 3])

### numpy.fromfunction

In [47]:
#it construct an array by executing a fnc over each cordinate

In [63]:
np.fromfunction(lambda i ,j: i==j ,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [68]:
np.fromfunction(lambda i ,j: i*j ,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [77]:
np.fromfunction(lambda i,j,k,l:i*j*k*l,(2,3,3,3),dtype=int)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 1, 2],
         [0, 2, 4]],

        [[0, 0, 0],
         [0, 2, 4],
         [0, 4, 8]]]])

In [88]:
#create a new 1d array from iterable obj
iterable=(i*i for i in range(4))
iterable

<generator object <genexpr> at 0x0000017520FB1740>

In [89]:
np.fromiter(iterable,dtype=int)

array([0, 1, 4, 9])

In [91]:
x1=np.array([1,12,34,4])
x2=np.array([1,5,3423,4])
x3=np.array([1,14,343,4])
x4=np.array([1,13,324,4])

In [95]:
record=np.core.records.fromarrays([x1,x2,x3,x4],names="a,b,c,d")

### data types

In [112]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(mat)
print(f"type {type(mat)}")
print(f"dimension of array is {mat.ndim}")
print("-----------")
print(f"{mat}")
print("-----------")
print(f"dtype is {mat.dtype}")

type <class 'numpy.ndarray'>
dimension of array is 2
-----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------
dtype is int32


### arange and linspace

In [115]:
list(range(1,2,3.4))#it doesnt work with  floating point

TypeError: 'float' object cannot be interpreted as an integer

In [116]:
np.arange(5,16,2.3) #it will deal with floating point no

array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [118]:
np.arange(18,1,-1)

array([18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [121]:
np.linspace(1,4,30)# 3rd one is not stepsize it is number size

array([1.        , 1.10344828, 1.20689655, 1.31034483, 1.4137931 ,
       1.51724138, 1.62068966, 1.72413793, 1.82758621, 1.93103448,
       2.03448276, 2.13793103, 2.24137931, 2.34482759, 2.44827586,
       2.55172414, 2.65517241, 2.75862069, 2.86206897, 2.96551724,
       3.06896552, 3.17241379, 3.27586207, 3.37931034, 3.48275862,
       3.5862069 , 3.68965517, 3.79310345, 3.89655172, 4.        ])

In [124]:
np.linspace(1,4,30,endpoint=False)# 3rd one is not stepsize it is number size

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9])

### matrix creation

In [132]:
print(np.zeros(3))

[0. 0. 0.]


In [140]:
np.zeros((2,1,2))

array([[[0., 0.]],

       [[0., 0.]]])

In [141]:
np.zeros((2,1,2))+1

array([[[1., 1.]],

       [[1., 1.]]])

In [143]:
np.ones((2,1,2))*4

array([[[4., 4.]],

       [[4., 4.]]])

In [144]:
np.ones((2,1,2))/12

array([[[0.08333333, 0.08333333]],

       [[0.08333333, 0.08333333]]])

In [145]:
np.empty((1,1))

array([[0.08333333]])

In [147]:
identity_mat=np.eye(4)
identity_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [151]:
np.logspace(2,3,num=4,base=5)

array([ 25.        ,  42.74939867,  73.10044346, 125.        ])

In [152]:
#scaler is a which has no dim
#vector is a which has min 2 dim

In [157]:
# assgn
# 1.
np.zeros(10)+5*2

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [158]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [160]:
lists=[1,12,3,4,5]
np.mat(lists)

matrix([[ 1, 12,  3,  4,  5]])

In [171]:
a=np.ones((4,5,2))
print(a.ndim)
print(a.shape)
print(a.dtype)

3
(4, 5, 2)
float64


In [172]:
x1=np.ones((3,3,3))
x2=np.ones((3,3,3))
x1+x2

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

### reshape,diag

In [189]:
x=np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [191]:
x.reshape(3,4,1,1)

array([[[[ 0]],

        [[ 1]],

        [[ 2]],

        [[ 3]]],


       [[[ 4]],

        [[ 5]],

        [[ 6]],

        [[ 7]]],


       [[[ 8]],

        [[ 9]],

        [[10]],

        [[11]]]])

In [192]:
np.diag(x)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11]])

In [204]:
x=np.array([[1,2,3],[4,5,6]])
np.diag(np.diag(x))

array([[1, 0],
       [0, 5]])

In [211]:
#create a 2d array with the flattened input as a diagonal
np.diagflat([[1,2],[3,4]],k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [225]:
np.tri(5,5,0,dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [231]:
np.tri(3,4,k=1)

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [232]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [233]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [239]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

### random number generation

In [265]:
print("rand no gen from uniform distribution")
np.random.rand(2,1)#it will generate from 0 to 1

rand no gen from uniform distribution


array([[0.51963892],
       [0.53596222]])

In [268]:
print("no from normal distribution with mean 0 and std 1")
print(np.random.randn(3,3,3))

no from normal distribution with mean 0 and std 1
[[[ 1.13532991 -0.16476282  2.30252047]
  [-0.94666815  0.06637766 -0.56546524]
  [-0.71805859 -0.77554004  0.94938579]]

 [[ 0.01587707  0.65258024  1.18147712]
  [-1.01351576  0.8534275   0.66855984]
  [-0.51350923  2.69632204  0.41528272]]

 [[-1.11900395  0.38575765  0.05722865]
  [-2.16453645 -0.12292836  0.20297283]
  [ 0.87081863  1.48814034 -1.9482457 ]]]


In [271]:
np.random.randint(2,90,(4,4,4))

array([[[16, 29, 46, 30],
        [57, 75, 64, 52],
        [58, 57, 61, 11],
        [14, 79, 76, 20]],

       [[80, 34, 70, 46],
        [66,  8, 56, 12],
        [47, 60, 63, 27],
        [56, 66, 28, 43]],

       [[89, 41, 65, 79],
        [31, 65, 67,  4],
        [74,  8, 17, 24],
        [42, 67, 16, 56]],

       [[22, 17, 28, 10],
        [ 3, 14, 37, 86],
        [46, 72, 81,  8],
        [57, 73, 51, 41]]])

### reshaping

In [34]:
import numpy as np
from numpy.random import randn as rn
r=rn(1,3,3).reshape(3,3)

In [60]:
np.sort(r,axis=0)

array([[-0.64396046,  0.50909688, -1.00666594],
       [-0.03094769,  0.96825771, -0.64600047],
       [ 0.24581557,  1.15997178,  1.30206836]])

In [61]:
r.max()

1.3020683610710866

In [63]:
r

array([[-0.64396046,  1.15997178,  1.30206836],
       [-0.03094769,  0.50909688, -0.64600047],
       [ 0.24581557,  0.96825771, -1.00666594]])

In [62]:
r.min()

-1.0066659351983598

In [65]:
r.argmax(axis=1)#return the index of the max value

array([2, 1, 1], dtype=int64)

### Indexing and slicing

In [66]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[10]

10

In [68]:
#slicing concept
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[3:5]

array([3, 4])

In [70]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [71]:
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [73]:
arr[2:10:2]

array([2, 4, 6, 8])

In [95]:
mat=np.linspace(10,100,45).reshape(3,5,3)
mat

array([[[ 10.        ,  12.04545455,  14.09090909],
        [ 16.13636364,  18.18181818,  20.22727273],
        [ 22.27272727,  24.31818182,  26.36363636],
        [ 28.40909091,  30.45454545,  32.5       ],
        [ 34.54545455,  36.59090909,  38.63636364]],

       [[ 40.68181818,  42.72727273,  44.77272727],
        [ 46.81818182,  48.86363636,  50.90909091],
        [ 52.95454545,  55.        ,  57.04545455],
        [ 59.09090909,  61.13636364,  63.18181818],
        [ 65.22727273,  67.27272727,  69.31818182]],

       [[ 71.36363636,  73.40909091,  75.45454545],
        [ 77.5       ,  79.54545455,  81.59090909],
        [ 83.63636364,  85.68181818,  87.72727273],
        [ 89.77272727,  91.81818182,  93.86363636],
        [ 95.90909091,  97.95454545, 100.        ]]])

In [98]:
mat[:,:2]

array([[[10.        , 12.04545455, 14.09090909],
        [16.13636364, 18.18181818, 20.22727273]],

       [[40.68181818, 42.72727273, 44.77272727],
        [46.81818182, 48.86363636, 50.90909091]],

       [[71.36363636, 73.40909091, 75.45454545],
        [77.5       , 79.54545455, 81.59090909]]])